# Generated by Django 5.1.1 on 2024-11-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="theatre.actor"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="theatre.genre"
            ),
        ),
    ]
